apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: prometheus-tg-config
  namespace: monitoring
spec:
  targetReference:
    name: monitoring-kube-prometheus-prometheus
  defaultConfiguration:
    targetType: ip
